### ISSUE TITLE
Melhorar a classe Parameters

### ISSUE THREAD

**Issue by igobrilhante** [ARiDa/moap#2]
Como melhorar esta classe para que possamos validar as entradas para cada método que utilize essa classe.

Ex.

Alg requer params A:string B:int

User passa A:int C:string

Um método deveria ser utilizado para validar os parâmetros de entrada.

**Comment by franzejr** [comment]
Não já há o areParametersValids? Vc queria que ao instanciasse já fosse feita a verificação?
